version: '3'
services:
  node-app:
    container_name: node-app
    build:
      context: ../..
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /home/jae/projects:/var/www
    restart: always